"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var Result, processCustomValidate;
  Result = require('../result');

  processCustomValidate = function processCustomValidate(result, field, fields, validators) {
    var ei, name, params, si, validate;

    if (!field.hasOwnProperty('validate')) {
      return;
    }

    validate = field.validate.trim();
    si = validate.indexOf('(');
    ei = validate.indexOf(')');

    if (!(!~si && !~ei || ~si && ei === validate.length - 1)) {
      return result.error(function (path) {
        return Result.prop('validate')(path);
      }, 'dsc.invalidValue', {
        value: validate
      });
    } else {
      if (~si) {
        name = validate.substr(0, si);
        params = validate.substr(si + 1, ei - si - 1);
      } else {
        name = validate;
      }

      if (!validators.hasOwnProperty(name)) {
        return result.error(function (path) {
          return Result.prop('validate')(path);
        }, 'dsc.unknownValidator', {
          value: validate
        });
      } else {
        return result.context(function (path) {
          return Result.prop('validate')(path);
        }, function () {
          return validators[name].call(fields, result, field, params, validate); // processCustomValidate =
        });
      }
    }
  }; // ----------------------------


  module.exports = processCustomValidate;
}).call(void 0);