"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var ConfigContainer, extend;
  ConfigContainer = require('./configContainer');

  extend = function extend(DSGulpBuilder) {
    var ref, taskClass, taskClassDef, taskName;
    ref = require('require-dir')('./tasks', {
      recurse: false
    });

    for (taskName in ref) {
      taskClassDef = ref[taskName];

      (function (taskName, taskClassDef) {
        var taskClass;
        taskClass = taskClassDef(DSGulpBuilder);
        return ConfigContainer.prototype[taskName[0].toLowerCase() + taskName.substr(1)] = function () {
          var arg, args, i, len, newInstance;
          newInstance = Object.create(taskClass.prototype);
          args = [this];

          for (i = 0, len = arguments.length; i < len; i++) {
            arg = arguments[i];
            args.push(arg);
          }

          taskClass.apply(newInstance, args);
          return newInstance;
        };
      })(taskName, taskClassDef);
    }

    taskClass = require('./compileConfig')(DSGulpBuilder);

    DSGulpBuilder.Task.prototype.compileConfig = function () {
      var arg, args, i, len, newInstance;
      newInstance = Object.create(taskClass.prototype);
      args = [this];

      for (i = 0, len = arguments.length; i < len; i++) {
        arg = arguments[i];
        args.push(arg);
      }

      taskClass.apply(newInstance, args);
      return newInstance;
    };

    return ConfigContainer; // extend =
  }; // ----------------------------


  extend["default"] = extend;
  module.exports = extend;
}).call(void 0);