"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$accessBuilder, freezeBitArray, _modify;

  freezeBitArray = function freezeBitArray(ba) {
    // _buildList() чтобы тесты срабатывали когда маски сравниваются с тегами
    return ba._buildList().lock(); // (ba) ->
  };

  _modify = function modify(body) {
    var access, r, ref, required, update, view;
    view = r.view.clone();
    update = r.update.clone();
    required = r.required.clone();
    access = (ref = r.access) != null ? ref.clone() : void 0;
    body(view, update, required, access);
    r = {
      view: view.lock(),
      update: update.lock(),
      required: required.lock(),
      access: access != null ? access.lock() : void 0
    };
    r.modify = _modify;
    return r;
  };

  $$accessBuilder = function $$accessBuilder(type, fieldsProp, access, isDoc) {
    var res; // TODO: Wrap and check result

    res = typeof access === 'function' ? function (fields) {
      var r;
      r = access.apply(this, arguments); // (type, fieldsProp, access) ->

      if (isDoc) {
        if (!r.actions) {
          r.actions = type.actions.$$tags.all;
        }

        r.view = r.view ? freezeBitArray(r.view.add('#system-options', {
          strict: false
        })) : type[fieldsProp].$$tags.all;
        r.update = r.update ? (r.update = r.update.remove('#system+#computed', {
          strict: false
        }), type.actions["delete"] && r.actions.get(type.actions["delete"].$$index) ? r.update = r.update.add('deleted') : void 0, freezeBitArray(r.update)) : type[fieldsProp].$$calc('(#all-#system-#computed),deleted', {
          // в тестах может не быть системных действий
          strict: false
        });

        if (!r.required) {
          r.required = freezeBitArray(r.required || type[fieldsProp].$$tags.required);
        }
      } else {
        if (!r.view) {
          r.view = type[fieldsProp].$$tags.all;
        }

        if (!r.update) {
          r.update = type[fieldsProp].$$tags.all;
        }

        if (!r.required) {
          r.required = type[fieldsProp].$$tags.required;
        }
      }

      r.modify = _modify;
      return r; // (fields) ->
    } : function () {
      var allAccess;
      allAccess = {
        view: type[fieldsProp].$$calc('#all-options', {
          strict: false
        }),
        update: type[fieldsProp].$$calc('(#all-#system-#computed),deleted', {
          strict: false
        }),
        required: type[fieldsProp].$$tags.required
      };

      if (isDoc) {
        allAccess.actions = type.actions.$$tags.all;
      }

      allAccess.modify = _modify;
      return function (doc) {
        return allAccess; // (type, fieldsProp, access) ->
      };
    }();
    return res;
  }; // ----------------------------


  module.exports = $$accessBuilder;
}).call(void 0);