"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$accessBuilder;

  $$accessBuilder = function $$accessBuilder(type, fieldsProp, access, addActions) {
    if (typeof access === 'function') {
      // TODO: Wrap and check result
      return access; // (type, fieldsProp, access) ->
    } else {
      return function () {
        var allAccess, exceptSystem;
        exceptSystem = type[fieldsProp].$$tags.hasOwnProperty('system') ? type[fieldsProp].$$tags.system.invert() : type[fieldsProp].$$tags.all;
        allAccess = {
          view: exceptSystem,
          update: exceptSystem
        };

        if (addActions) {
          allAccess.actions = type.actions.$$tags.all;
        }

        if (type.hasOwnProperty('actions')) {
          allAccess.actions = type.actions.$$tags.all;
        }

        return function (doc) {
          return allAccess; // (type, fieldsProp, access) ->
        };
      }();
    }
  }; // ----------------------------


  module.exports = $$accessBuilder;
}).call(void 0);