"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

// Generated by CoffeeScript 2.5.1
(function () {
  var $$editValidatorBuilderBuilder, Result, cloneDeep, invalidArg, unknownOption;
  Result = require('../../result');
  cloneDeep = require('lodash/cloneDeep');

  var _require = require('../../utils/_err');

  invalidArg = _require.invalidArg;
  unknownOption = _require.unknownOption;

  $$editValidatorBuilderBuilder = function $$editValidatorBuilderBuilder(type, fieldsProp, access, docLevelValidate) {
    return function () {
      var _this = this;

      var prevBusinessResult, prevModel;
      prevModel = void 0;
      prevBusinessResult = void 0;
      return function (fields, options) {
        var beforeAction, beforeSave, goodForAction, localResult, messages, oldSave, optName, optValue, r, save, validate;
        beforeSave = false;
        beforeAction = false;

        if (options !== void 0) {
          if (!(_typeof(options) === 'object' && options !== null && !Array.isArray(options))) {
            invalidArg('options', options);
          }

          for (optName in options) {
            optValue = options[optName];

            switch (optName) {
              case 'beforeSave':
                beforeSave = !!optValue;
                break;

              case 'beforeAction':
                beforeAction = !!optValue;
                break;

              default:
                unknownOption(optName);
            }
          }
        }

        if (fields !== prevModel) {
          prevBusinessResult = void 0;
          prevModel = fields;
        }

        validate = type["_".concat(fieldsProp, "Validate")];
        messages = {};
        r = access.call(_this, fields);
        save = true;
        goodForAction = beforeAction;
        localResult = new Result();

        localResult.error = function () {
          // перехватываем сообщения об ошибках
          var msg;
          msg = Result.prototype.error.apply(localResult, arguments);

          if (msg.type === 'error') {
            goodForAction = false;

            if (msg.code !== 'validate.requiredField') {
              // localResult.error = () ->
              save = false;
            }
          }
        };

        validate(localResult, fields, void 0, r.update, r.required, beforeSave || beforeAction ? void 0 : fields.$$touched, false, beforeAction);
        oldSave = save;

        if (localResult.isError) {
          localResult.messages.forEach(function (msg) {
            var path;

            if (path = msg.path) {
              !messages[path] || msg.type === 'error' && messages[path].type !== 'error' ? messages[path] = msg : void 0;
            } else {
              (messages[''] || (messages[''] = [])).push(msg);
            }
          });

          if (prevBusinessResult != null) {
            prevBusinessResult.messages.forEach(function (msg) {
              var path;

              if (path = msg.path) {
                !messages[path] ? messages[path] = msg : void 0;
              } else {
                (messages[''] || (messages[''] = [])).push(msg);
              }
            });
          }
        } else if (beforeAction) {
          if (typeof docLevelValidate === 'function') {
            localResult.messages.length = 0;
            docLevelValidate.call(_this, localResult, fields);

            if (localResult.isError) {
              goodForAction = false;
            }

            localResult.messages.forEach(function (msg) {
              var path;

              if (path = msg.path) {
                !messages[path] || msg.type === 'error' && messages[path].type !== 'error' ? messages[path] = msg : void 0;
              } else {
                (messages[''] || (messages[''] = [])).push(msg);
              }
            });
            prevBusinessResult = localResult.messages.length > 0 ? localResult : void 0;
          }
        }

        return {
          save: oldSave,
          goodForAction: goodForAction,
          messages: messages // (fields) ->  # ->

        };
      };
    };
  }; // ----------------------------


  module.exports = $$editValidatorBuilderBuilder;
}).call(void 0);