"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

// Generated by CoffeeScript 2.5.1
(function () {
  var _$$fixBuilder, EMPTY, defaultInit, hasOwnProperty, invalidArg, unknownOption;

  var _require = require('../../utils/_err');

  invalidArg = _require.invalidArg;
  unknownOption = _require.unknownOption;
  defaultInit = {
    string: '',
    text: '',
    "boolean": false,
    integer: 0,
    "double": 0,
    //  decimal: '0'
    time: null,
    date: null,
    timestamp: null
  }; //  json:
  //  blob:
  //  uuid:
  //  enum:

  EMPTY = {};
  hasOwnProperty = Object.prototype.hasOwnProperty;

  _$$fixBuilder = function $$fixBuilder(fields) {
    var field, i, len, newFuncs, ref;
    newFuncs = [];
    ref = fields.$$list;

    for (i = 0, len = ref.length; i < len; i++) {
      field = ref[i];

      (function () {
        var copyVal, fix, index, init, name, newVal;
        name = field.name;
        init = void 0;
        index = field.$$index;

        if (field.type === 'structure') {
          init = _$$fixBuilder(field.fields);
        } else if (field.type === 'subtable') {
          if (field.required) {
            (function (fields) {
              init = function init(options) {
                return [fields.$$fix(EMPTY, options)];
              };
            })(field.fields);
          } else {
            init = [];
          }
        } else if (field.hasOwnProperty('init')) {
          init = field.init;
        } else if (field["null"]) {
          init = null;
        } else if (defaultInit.hasOwnProperty(field.type)) {
          init = defaultInit[field.type];
        } else if (field.type === 'enum') {
          init = field["enum"].$$list[0].name;
        } else {
          init = null;
        }

        if (typeof init === 'function') {
          newVal = function newVal(res, options) {
            res[name] = init(options);
          };
        } else {
          newVal = function newVal(res) {
            res[name] = init;
          };
        }

        if (field.type === 'structure') {
          fix = _$$fixBuilder(field.fields);

          copyVal = function copyVal(res, fieldsLevel, options) {
            res[name] = fix(fieldsLevel[name], options);
          };
        } else if (field.type === 'subtable') {
          fix = field.fields.$$fix;

          copyVal = function copyVal(res, fieldsLevel, options) {
            var row;

            res[name] = function () {
              var j, len1, ref1, results;
              ref1 = fieldsLevel[name];
              results = [];

              for (j = 0, len1 = ref1.length; j < len1; j++) {
                row = ref1[j];
                results.push(fix(row, options));
              }

              return results;
            }();
          };
        } else {
          copyVal = function copyVal(res, fieldsLevel) {
            return res[name] = fieldsLevel[name];
          };
        }

        return newFuncs.push(function (res, fieldsLevel, mask, options) {
          if (!mask || mask.get(index)) {
            if (hasOwnProperty.call(fieldsLevel, name)) {
              return copyVal(res, fieldsLevel, options);
            } else {
              return newVal(res, options);
            }
          }
        });
      })();
    }

    return function (fieldsLevel, options) {
      var edit, mask, optName, optValue, res;
      edit = false;
      mask = void 0;

      if (options !== void 0) {
        if (!(_typeof(options) === 'object' && options !== null && !Array.isArray(options))) {
          invalidArg('options', options);
        }

        for (optName in options) {
          optValue = options[optName];

          switch (optName) {
            case 'edit':
              edit = optValue;
              break;

            case 'mask':
              mask = optValue;
              break;

            default:
              unknownOption(optName);
          }
        }
      }

      res = {};
      newFuncs.forEach(function (f) {
        f(res, fieldsLevel, mask, options);
      });

      if (edit) {
        res.$$touched = {};
      }

      return res; // () ->
    };
  }; // ----------------------------


  module.exports = _$$fixBuilder;
}).call(void 0);