"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$getBuilder;

  $$getBuilder = function $$getBuilder(fields) {
    return function (fieldsLevel, mask, options) {
      // (fields) ->
      return fields.$$fix(fieldsLevel, Object.assign({}, options, {
        mask: mask
      })); // (options) ->
    };
  }; // ----------------------------


  module.exports = $$getBuilder;
}).call(void 0);