"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$getBuilder;

  $$getBuilder = function $$getBuilder(fields) {
    var mask, ref;
    mask = ((ref = fields.$$tags) != null ? ref.system : void 0) ? {
      mask: fields.$$tags.system.invert()
    } : void 0;
    return function (fieldsLevel, mask, options) {
      // (fields) ->
      return fields.$$fix(fieldsLevel, Object.assign({}, options, {
        mask: mask
      })); // (options) ->
    };
  }; // ----------------------------


  module.exports = $$getBuilder;
}).call(void 0);