"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$newBuilder, EMPTY;
  EMPTY = {};

  $$newBuilder = function $$newBuilder(fields) {
    var mask, ref;
    mask = ((ref = fields.$$tags) != null ? ref.system : void 0) ? {
      mask: fields.$$tags.system.invert()
    } : void 0;

    if (mask && fields.state) {
      mask.mask.set(fields.state.$$index);
    }

    return function (options) {
      // (fields) ->
      return fields.$$fix(EMPTY, Object.assign({}, mask, options)); // (options) ->
    };
  }; // ----------------------------


  module.exports = $$newBuilder;
}).call(void 0);