"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$rightsBuilder;

  $$rightsBuilder = function $$rightsBuilder(docDesc, rootRights, docRights) {
    var funcs;
    funcs = [];

    if (rootRights != null ? rootRights.fullRights : void 0) {
      funcs.push(rootRights.fullRights);
    }

    if (rootRights != null ? rootRights.fullRights : void 0) {
      funcs.push(rootRights.relations);
    }

    if (rootRights != null ? rootRights.fullRights : void 0) {
      funcs.push(rootRights.rights);
    }

    if (docRights != null ? docRights.fullRights : void 0) {
      funcs.push(docRights.fullRights);
    }

    if (docRights != null ? docRights.fullRights : void 0) {
      funcs.push(docRights.relations);
    }

    if (docRights != null ? docRights.fullRights : void 0) {
      funcs.push(docRights.rights);
    }

    if (funcs.length > 0) {
      // args: {doc, user, view, update, actions, relations, fullFields, fullActions}
      return function (args) {
        args.docDesc = docDesc;
        funcs.forEach(function (f) {
          return f(args); // (args) ->
        });
      };
    }
  }; // ----------------------------


  module.exports = $$rightsBuilder;
}).call(void 0);