"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$setBuilder;

  $$setBuilder = function $$setBuilder(fields) {
    return function (fieldsLevel, update, options) {
      // (fields) ->
      return fields.$$fix(fieldsLevel, Object.assign({}, options, {
        update: update
      })); // (options) ->
    };
  }; // ----------------------------


  module.exports = $$setBuilder;
}).call(void 0);