"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$getBuilder;

  $$getBuilder = function $$getBuilder(docDesc) {
    return function (fieldsLevel, updateMask, options) {
      // (fields) ->
      var access, mask;

      if (!updateMask) {
        access = docDesc.$$access(fieldsLevel);
        mask = docDesc.fields.$$calc('id,rev,deleted').or(access.update);
      }

      return docDesc.fields.$$fix(fieldsLevel, Object.assign({}, options, {
        mask: mask,
        newVal: false // (options) ->

      }));
    };
  }; // ----------------------------


  module.exports = $$getBuilder;
}).call(void 0);