"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$updateBuilder;

  $$updateBuilder = function $$updateBuilder(docDesc) {
    return function (fieldsLevel, updateMask, options) {
      // (fields) ->
      var access, mask;

      if (!updateMask) {
        access = docDesc.$$access(fieldsLevel);
        mask = docDesc.fields.$$calc('id,rev,deleted', {
          strict: false
        }).or(access.update);
      } else {
        mask = updateMask;
      }

      return docDesc.fields.$$fix(fieldsLevel, Object.assign({}, options, {
        mask: mask,
        newVal: false // (options) ->

      }));
    };
  }; // ----------------------------


  module.exports = $$updateBuilder;
}).call(void 0);