"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var $$updateBuilder;

  $$updateBuilder = function $$updateBuilder(docDesc) {
    return function (fieldsLevel, updateMask, options) {
      // (fields) ->
      var access, mask, noRev;

      if (options != null ? options.hasOwnProperty('noRev') : void 0) {
        noRev = !!options.noRev;
        options = Object.assign({}, options);
        delete options.noRev;
      }

      if (!updateMask) {
        access = docDesc.$$access(fieldsLevel);
        mask = access.update.add('id, delete', {
          strict: false
        });

        if (noRev) {
          mask.remove('rev', {
            strict: false
          });
        }

        mask.lock();
      } else {
        mask = updateMask;
      }

      return docDesc.fields.$$fix(fieldsLevel, Object.assign({}, options, {
        mask: mask,
        newVal: false // (options) ->

      }));
    };
  }; // ----------------------------


  module.exports = $$updateBuilder;
}).call(void 0);