"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  exports.createIndex = 0;
  exports.retrieveIndex = 1;
  exports.updateIndex = 2;
  exports.deleteIndex = 3;
  exports.restoreIndex = 4;
}).call(void 0);