"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

// Generated by CoffeeScript 2.5.1
(function () {
  var Result, copyOptions;
  Result = require('../result');

  copyOptions = function copyOptions(result, map) {
    var item;
    item = void 0;
    return result.context(function (path) {
      return Result.prop('options', Result.item(item.name))(path);
    }, function () {
      var i, len, ref, results, value;
      ref = map.$$list;
      results = [];

      for (i = 0, len = ref.length; i < len; i++) {
        item = ref[i];

        if (!item.$$src.hasOwnProperty('options')) {
          continue;
        }

        value = item.$$src.options;

        if (!(_typeof(value) === 'object' && value !== null && !Array.isArray(value))) {
          results.push(result.error('dsc.invalidValue', {
            value: value
          }));
        } else {
          results.push(item.options = value);
        }
      }

      return results;
    });
  }; //---------------------------


  module.exports = copyOptions;
}).call(void 0);