"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var Result, bitArray, compileTags, copyExtra, processActions, sortedMap;
  Result = require('../result');
  sortedMap = require('../sortedMap');
  bitArray = require('../bitArray');

  var _require = require('../tags');

  compileTags = _require.compile;
  copyExtra = require('./_copyExtra');

  processActions = function processActions(result, doc, noSystemItems) {
    if (!(doc.$$src.hasOwnProperty('actions') || !noSystemItems)) {
      // processActions =
      return {
        $$list: [],
        $$tags: {
          all: new bitArray({
            $$list: []
          })
        }
      };
    }

    return result.context(Result.prop('actions'), function () {
      // processActions =
      var action, res, sortedMapOpts;
      sortedMapOpts = {
        index: true,
        getValue: function getValue(result, value, res) {
          if (typeof value === 'function') {
            // TODO: Check number of parameters in given function
            res.value = value;
            return true;
          }

          return false;
        }
      };

      if (!noSystemItems) {
        sortedMapOpts.before = [{
          // TODO: Think of replacement of 'value'
          name: 'create',
          tags: 'system',
          value: function value() {}
        }, {
          name: 'retrieve',
          tags: 'system',
          value: function value() {}
        }, {
          name: 'update',
          tags: 'system',
          value: function value() {}
        }, {
          name: 'delete',
          tags: 'system',
          value: function value() {}
        }, {
          name: 'restore',
          tags: 'system',
          value: function value() {}
        }];
        sortedMapOpts.reservedName = ['create', 'retrieve', 'update', 'delete', 'restore'];
      }

      res = sortedMap(result, doc.$$src.actions || {}, sortedMapOpts);

      if (!result.isError) {
        action = void 0;
        result.context(function (path) {
          return Result.prop(action.name)(path);
        }, function () {
          var i, len, ref;
          ref = res.$$list;

          for (i = 0, len = ref.length; i < len; i++) {
            action = ref[i];

            if (action.hasOwnProperty('$$src')) {
              if (!action.$$src.hasOwnProperty('value')) {
                result.error('dsc.missingProp', {
                  value: 'value'
                });
              } else if (typeof action.$$src.value !== 'function') {
                result.error('dsc.invalidValue', {
                  value: action.$$src.value
                });
              } else {
                // TODO: Check number of parameters in given function
                action.value = action.$$src.value; // result.context
              }
            }
          }
        });
        copyExtra(result, res);
        compileTags(result, res);
        sortedMap.finish(result, res, {
          skipProps: ['tags']
        });

        if (!result.isError) {
          // processActions =
          return res;
        }
      }
    });
  }; // ----------------------------


  module.exports = processActions;
}).call(void 0);