"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var Result, compileTags, compileType, flatMap, processFields, typeProps;
  Result = require('../result');
  flatMap = require('../flatMap');

  var _require = require('../types');

  compileType = _require.compile;
  typeProps = _require.compile._typeProps;

  var _require2 = require('../tags');

  compileTags = _require2.compile;

  processFields = function processFields(result, doc, config) {
    if (!doc.$$src.hasOwnProperty('fields')) {
      result.error('dsc.missingProp', {
        value: 'fields'
      });
      return;
    }

    return result.context(Result.prop('fields'), function () {
      // processFields
      var _processLevel2, res;

      res = flatMap(result, doc.$$src.fields, 'fields', {
        index: true,
        mask: true
      });

      if (!result.isError) {
        _processLevel2 = function _processLevel(level) {
          var field;
          field = void 0;
          result.context(function (path) {
            return Result.item(field.name)(path);
          }, function () {
            var i, j, len, len1, prop, ref, udt, udtList;
            ref = level.$$list;

            for (i = 0, len = ref.length; i < len; i++) {
              field = ref[i];
              result.isError = false;
              compileType(result, field.$$src, field, {
                context: 'field'
              });

              if (field.hasOwnProperty('udType') && config.hasOwnProperty('udtypes')) {
                // missing 'udtypes' means that udtypes compilation failed
                if (!config.udtypes.hasOwnProperty(field.udType)) {
                  result.error('dsc.unknownType', {
                    value: field.udType
                  });
                } else {
                  udt = config.udtypes[field.udType];
                  field.type = udt.type;

                  for (j = 0, len1 = typeProps.length; j < len1; j++) {
                    prop = typeProps[j];

                    if (udt.hasOwnProperty(prop)) {
                      field[prop] = udt[prop];
                    }
                  }

                  udtList = [udt.name];

                  while (udt.hasOwnProperty('udType')) {
                    udt = config.udtypes[udt.udType];
                    udtList.push(udt.name);
                  }

                  field.udType = udtList;
                }
              }

              if (!result.isError) {
                if (field.hasOwnProperty('fields')) {
                  result.context(Result.prop('fields'), function () {
                    return _processLevel2(field.fields); // result.context
                    // _processLevel =
                  });
                }
              }
            }
          });
        };

        _processLevel2(res);

        compileTags(result, res);
        flatMap.finish(result, res, 'fields', {
          skipProps: ['tags']
        });

        if (!result.isError) {
          // result.context
          return res;
        }
      }
    });
  }; // ----------------------------


  module.exports = processFields;
}).call(void 0);