"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var Result, processValidate;
  Result = require('../result');

  processValidate = function processValidate(result, fields) {
    var processLevel;
    return processLevel = void 0;
  }; // ----------------------------


  module.exports = processValidate;
}).call(void 0);