"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  var Result, processFields, processUdtypeFields, sortedMap;
  Result = require('../result');
  sortedMap = require('../sortedMap');
  processFields = require('./_processFields');

  processUdtypeFields = function processUdtypeFields(result, config) {
    var _buildOrder2, i, len, order, ref, stack, udType;

    if (result.isError) {
      return;
    }

    stack = [];
    order = [];

    _buildOrder2 = function _buildOrder(udType) {
      var level = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 0;

      if (~stack.indexOf(udType)) {
        result.error('dsc.cycledUdtypeDefinition', {
          type: udType
        });
        return;
      }

      stack.push(udType.name);
      result.context(Result.prop(level === 0 ? 'udtypes' : 'fields'), function () {
        var item;
        item = void 0;
        return result.context(function (path) {
          return Result.prop(item.name)(path);
        }, function () {
          var i, len, ref, results;
          ref = udType.fields;
          results = [];

          for (i = 0, len = ref.length; i < len; i++) {
            item = ref[i];

            if (item.hasOwnProperty('fields')) {
              results.push(_buildOrder2(item, level + 1));
            }
          }

          return results;
        });
      });
      order.push(udType); // udtype с fields используемые в этом типе должны идти раньше

      return stack.pop();
    };

    ref = config.udtypes.$$list;

    for (i = 0, len = ref.length; i < len; i++) {
      udType = ref[i];

      if (udType.hasOwnProperty('fields')) {
        if (!~order.indexOf(udType.name)) {
          _buildOrder2(udType);
        }
      }
    }

    udType = void 0;
    result.context(Result.prop('udtypes'), function () {
      return result.context(function (path) {
        return Result.prop(udType.name)(path);
      }, function () {
        var _clearIndex2, j, len1, results;

        results = [];

        for (j = 0, len1 = order.length; j < len1; j++) {
          udType = order[j];
          udType.fields = processFields(result, udType, config, 'fields', true);
          delete udType.fields.$$flat; // это не самостатоятельная структура.  она будет вставляться в иерархию полей

          delete udType.fields.$$tags;

          _clearIndex2 = function _clearIndex(list) {
            var item, k, len2, results1;
            results1 = [];

            for (k = 0, len2 = list.length; k < len2; k++) {
              item = list[k];
              delete item.$$index;

              if (item.fields) {
                results1.push(_clearIndex2(item.fields.$$list));
              } else {
                results1.push(void 0);
              }
            }

            return results1;
          };

          results.push(_clearIndex2(udType.fields.$$list));
        }

        return results;
      });
    });

    if (!result.isError) {
      sortedMap.finish(result, config.udtypes);
    }
  }; // ----------------------------


  module.exports = processUdtypeFields;
}).call(void 0);