"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  // имя документа - это несколько namespace'ов разделенных точками:
  // - namespace'ы начинаются с маленьких букв и содержит буквы и цифры
  // - имя документа начинается с большой буквы и содержит буквы и цифры
  var checkItemName;

  checkItemName = function checkItemName(value) {
    return typeof value === 'string' && /^[A-Z][a-zA-Z0-9_]*$/.test(value);
  }; // ----------------------------


  module.exports = checkItemName;
}).call(void 0);