"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  // имя документа - это несколько namespace'ов разделенных точками:
  // - namespace'ы начинаются с маленьких букв и содержит буквы и цифры
  // - имя документа начинается с большой буквы и содержит буквы и цифры
  var checkDocumentName;

  checkDocumentName = function checkDocumentName(value) {
    return typeof value === 'string' && /^([a-z][a-zA-Z0-9]*\.)*[A-Z][a-zA-Z0-9]*$/.test(value);
  }; // ----------------------------


  module.exports = checkDocumentName;
}).call(void 0);