"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  // имя ud типа - это несколько namespace'ов разделенных точками:
  // - namespace'ы начинаются с маленьких букв и содержит буквы и цифры
  // - имя документа начинается с маленьких букв и содержит буквы и цифры
  var checkUDTypeName;

  checkUDTypeName = function checkUDTypeName(value) {
    return typeof value === 'string' && /^([a-z][a-zA-Z0-9]*\.)*[a-z][a-zA-Z0-9]*$/.test(value);
  }; // ----------------------------


  module.exports = checkUDTypeName;
}).call(void 0);