"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  // имя поля документа может состояить только из английских букв и цифр. и начинаться может только
  // c маленькой буквы.
  var checkItemName;

  checkItemName = function checkItemName(value) {
    return typeof value === 'string' && /^[a-z][a-zA-Z0-9]*$/.test(value);
  }; // ----------------------------


  module.exports = checkItemName;
}).call(void 0);