"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  // TODO: заменить на Object.assign
  var extend;

  extend = function extend(dest) {
    var i, j, k, l, len, ref, ref1, s;

    for (i = j = 1, ref = arguments.length; j < ref; i = j += 1) {
      if (s = arguments[i]) {
        ref1 = Object.keys(s);

        for (l = 0, len = ref1.length; l < len; l++) {
          k = ref1[l];
          dest[k] = s[k];
        }
      }
    }

    return dest; // extend =
  }; // ----------------------------


  module.exports = extend;
}).call(void 0);