"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

// Generated by CoffeeScript 2.5.1
(function () {
  var lightClone;

  lightClone = function lightClone(obj) {
    var k, res, v;

    if (_typeof(obj) === 'object' && obj !== null) {
      if (Array.isArray(obj)) {
        return obj.slice(); // lightClone =
      } else {
        res = {};

        for (k in obj) {
          v = obj[k];

          if (!k.startsWith('$$')) {
            res[k] = v;
          }
        }

        return res; // lightClone =
      }
    } else {
      return obj; // lightClone =
    }
  }; // ----------------------------


  module.exports = lightClone;
}).call(void 0);