"use strict";

// Generated by CoffeeScript 2.5.1
(function () {
  module.exports = {
    err: require('./_err'),
    flatTree: require('./_flatTree'),
    deepClone: require('./_deepClone'),
    lightClone: require('./_lightClone'),
    checkItemName: require('./_checkItemName'),
    checkDocumentName: require('./_checkDocumentName'),
    checkUDTypeName: require('./_checkUDTypeName'),
    checkAPIName: require('./_checkAPIName'),
    prettyPrint: require('./_prettyPrint'),
    extend: require('./_extend'),
    lightStack: require('./_lightStack')
  };
}).call(void 0);